project 1:
we have list of recepies of making cupcake and muffincake with diffrent features like (flour,milk,suger,egg,baking powder,vanilla and salt ) we want to know if we have new recepies so its cupcake or muffincake?

<br>1- import libraries of numpy,matplotlib,sklearn.preprocessing,sklearn.cluster,sklearn</br>
<br>2-read the data of 'svm-muffin-cupcake.csv'</br>
<br>3-change muffin value to 0 and cupcake to 1.</br>
<br>4-choose x and y as features and labels. hint:(x=flour,milk,suger,butter,egg,baking powder,vanilla,salt and y=type)</br>
<br>5-devide data to train and test</br>
<br>6-import SVC and choosing valu of c=[1,10,100] and kernel=[linear,rbf,sigmoid,poly] for fitting data and print the result.also print the score foe each model.</br>
<br>7-choose the best model and put it in variable as model_best</br>
<br>8-store the prediction of our model and compare it with the y_test</br>
<br>9-check this recepi [flour=34, milk=17, suger=23, butter=11, egg=13,  baking powder=0,  vanilla=1,  salt=0]is for cupcake or muffin cake?</br>

In [2]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import scale
from sklearn.cluster import KMeans
from sklearn import svm
import pandas as pd

In [5]:
data = pd.read_csv(r'C:\Users\User\Downloads\SVM\SVC\SVC\svm-muffin-cupcake.csv')

data

type  flour  milk  suger  butter  egg  baking powder  vanilla  salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  cupcake     39     0     26      19   14              1        1     0
11  cupcake     42    21     16      10    8              3        0     0
12  cupcake     34    17     20      20    5              2        1     0
13  cupcake     39    13     17      19   10              1        1     0
14  cupcake     38    15     23      15    8              0        1     0
15  cupcake     42    18     25       9    5              1        0     0
16  cupcake     36    14     21      14   11              2        1     0
17  cupcake     38    15     31       8    6              1        1     0
18  cupcake     36    16     24      12    9              1        1     0
19  cupcake     34    17     23      11   13              0        1     0

In [11]:
data['type'].replace('Muffin', 0, inplace=True); data['type'].replace('cupcake', 1, inplace=True)
data

type  flour  milk  suger  butter  egg  baking powder  vanilla  salt
0      0     55    28      3       7    5              2        0     0
1      0     47    24     12       6    9              1        0     0
2      0     47    23     18       6    4              1        0     0
3      0     45    11     17      17    8              1        0     0
4      0     50    25     12       6    5              2        1     0
5      0     55    27      3       7    5              2        1     0
6      0     54    27      7       5    5              2        0     0
7      0     47    26     10      10    4              1        0     0
8      0     50    17     17       8    6              1        0     0
9      0     50    17     17      11    4              1        0     0
10     1     39     0     26      19   14              1        1     0
11     1     42    21     16      10    8              3        0     0
12     1     34    17     20      20    5              2        1     0
13     1     39    13     17      19   10              1        1     0
14     1     38    15     23      15    8              0        1     0
15     1     42    18     25       9    5              1        0     0
16     1     36    14     21      14   11              2        1     0
17     1     38    15     31       8    6              1        1     0
18     1     36    16     24      12    9              1        1     0
19     1     34    17     23      11   13              0        1     0

In [13]:
y = data['type']
x = data.drop(columns=['type'])

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [19]:
c = [1,10,100]
kernels = ['linear','poly','rbf','sigmoid']

for c_ in c:
    for k_ in kernels:
        model = svm.SVC(C=c_,kernel=k_,gamma='auto').fit(x_train,y_train)
        score = model.score(x_test, y_test)
        print(f'C value of {c_}, \nKernel: {k_}, Score={score}')

C value of 1, 
Kernel: linear, Score=1.0
C value of 1, 
Kernel: poly, Score=1.0
C value of 1, 
Kernel: rbf, Score=0.5
C value of 1, 
Kernel: sigmoid, Score=0.3333333333333333
C value of 10, 
Kernel: linear, Score=1.0
C value of 10, 
Kernel: poly, Score=1.0
C value of 10, 
Kernel: rbf, Score=0.5
C value of 10, 
Kernel: sigmoid, Score=0.3333333333333333
C value of 100, 
Kernel: linear, Score=1.0
C value of 100, 
Kernel: poly, Score=1.0
C value of 100, 
Kernel: rbf, Score=0.5
C value of 100, 
Kernel: sigmoid, Score=0.3333333333333333


In [21]:
model_ = svm.SVC(C=1,gamma='auto',kernel='linear').fit(x_train,y_train)

y_pred = model_.predict(x_test)

In [22]:
y_pred

array([0, 1, 1, 1, 0, 1], dtype=int64)

# Glass Prediction :)

In [29]:
data_glass = pd.read_csv(r"C:\Users\User\Documents\Datasets\glass.csv")

data_glass.head(100)
data_glass.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516523   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [60]:
x_ = pd.DataFrame(data_glass.drop(columns='Type'))
y_ = data_glass['Type']

y_.unique()

array([1, 2, 3, 5, 6, 7], dtype=int64)

In [61]:
x_train, x_test, y_train, y_test = train_test_split(x_, y_, test_size=0.3)

In [68]:
c = [1,10,100]
kernels = ['linear','poly','rbf','sigmoid']

for c_ in c:
    for k_ in kernels:
        model = svm.SVC(C=c_,kernel=k_,gamma='auto').fit(x_train,y_train)
        score = model.score(x_test, y_test)
        print(f'C value of {c_}, \nKernel: {k_}, Score={score}')

C value of 1, 
Kernel: linear, Score=0.5384615384615384
C value of 1, 
Kernel: poly, Score=0.6461538461538462
C value of 1, 
Kernel: rbf, Score=0.6
C value of 1, 
Kernel: sigmoid, Score=0.3230769230769231
C value of 10, 
Kernel: linear, Score=0.6461538461538462
C value of 10, 
Kernel: poly, Score=0.7076923076923077
C value of 10, 
Kernel: rbf, Score=0.6923076923076923
C value of 10, 
Kernel: sigmoid, Score=0.3230769230769231
C value of 100, 
Kernel: linear, Score=0.7076923076923077
C value of 100, 
Kernel: poly, Score=0.6461538461538462
C value of 100, 
Kernel: rbf, Score=0.7076923076923077
C value of 100, 
Kernel: sigmoid, Score=0.3230769230769231


In [69]:
best_model = svm.SVC(C=100,kernel='rbf',gamma='auto').fit(x_train,y_train)

y_pred = best_model.predict(x_train)
y_pred

array([7, 1, 1, 1, 7, 1, 1, 2, 1, 1, 2, 7, 1, 1, 6, 2, 2, 2, 7, 7, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 5, 7, 2, 1, 1, 2, 2, 2, 2, 2, 7, 6, 2, 2, 2,
       1, 1, 1, 1, 1, 2, 1, 5, 5, 1, 7, 2, 2, 2, 1, 1, 2, 7, 5, 2, 1, 2,
       1, 2, 2, 6, 6, 2, 6, 2, 2, 1, 1, 2, 2, 1, 7, 3, 2, 1, 1, 1, 1, 7,
       1, 1, 1, 7, 2, 2, 3, 1, 1, 2, 5, 5, 1, 2, 7, 2, 2, 2, 7, 2, 2, 2,
       2, 1, 5, 2, 1, 7, 1, 1, 1, 5, 1, 2, 1, 2, 2, 1, 2, 2, 7, 5, 1, 2,
       7, 1, 1, 1, 3, 1, 2, 7, 1, 2, 2, 2, 2, 2, 2, 6, 1], dtype=int64)

In [70]:
z = []
count = 0

for (x,y) in zip(y_test,y_pred):
    if x==y:
        count = count+1

right = len(y_test)-count

print(right/len(y_test))
#print(len(z)/len(y_test))

0.7692307692307693


In [59]:
nani

130    2
9      1
208    7
85     2
140    2
89     2
180    6
108    2
136    2
58     1
143    2
175    5
84     2
82     2
203    7
129    2
150    3
65     1
131    2
112    2
116    2
189    7
54     1
159    3
5      1
32     1
199    7
205    7
12     1
75     2
      ..
1      1
31     1
107    2
119    2
104    2
142    2
50     1
34     1
122    2
29     1
96     2
210    7
192    7
160    3
120    2
24     1
161    3
146    3
36     1
186    7
51     1
4      1
3      1
202    7
86     2
147    3
105    2
172    5
139    2
88     2
Name: Type, Length: 65, dtype: int64
[1 1 2 2 1 7 6 6 2 2 1 2 2 1 2 2 7 2 1 1 7 1 2 2 5 1 6 2 2 1 7 7 1 1 1 2 1
 1 2 2 7 1 2 5 6 1 1 5 6 1 2 1 1 1 1 2 1 1 7 5 2 1 3 2 1 7 1 2 2 5 2 2 1 2
 2 1 2 1 2 2 7 7 1 2 5 1 1 1 2 3 1 2 2 1 1 1 1 1 2 7 1 2 1 2 1 1 5 2 2 5 2
 2 2 1 2 1 2 1 6 7 7 1 7 6 6 1 1 1 2 7 2 1 7 2 3 1 1 7 1 5 1 2 2 1 2 7 1 2
 5]


UsageError: Line magic function `%c` not found.
