List Properties

In [8]:
data =[] 
for i in range(1,20,5):
    data.append(i)
print(data)

[1, 6, 11, 16]


In [14]:
import random
data = []
for i in range(10):
    data.append(random.randint(-50,50))
print(data)

[-18, -43, 11, 24, 26, -8, -36, -8, -47, 9]


In [13]:
import random
data = []
for i in range(10):
    data.append(random.uniform(-50,50))
print(data)

[-12.931066102988744, -49.28033976796553, -9.943177271825412, -42.59601609832527, 15.37750394390234, 31.602081631715492, -20.268184320804792, -4.147081320150328, -35.213484060545184, -31.274993686275486]


In [18]:
import numpy as np
data = []
data=np.array([-1, 22, 35, 4.34, 56, 6])
print (data)

[-1.   22.   35.    4.34 56.    6.  ]


In [22]:
data_arange = []
data_linspace = []
data_arange = np.arange(0, 11, 2, dtype=float)
print(data_arange)
data_linspace = np.linspace(0, 10, 5)
print(data_linspace)

[ 0.  2.  4.  6.  8. 10.]
[ 0.   2.5  5.   7.5 10. ]


In [39]:
data_randint = []
data_randn = []
data_randint = np.random.randint(-10, 10, 20)
print(data_randint)
data_randn = np.random.randn(10)
print(data_randn)


[-5  4 -8 -9 -8  7 -9  6  4 -2 -5 -2 -6 -6 -6  0  4 -4  5  2]
[-0.65400875 -0.25804442  0.47304563  0.36173806 -0.28905012  0.84632938
 -0.33361572  1.15236965 -1.15154527 -0.04323693]


Index of the list

In [52]:
x = [7, 14, 20, 1, -16, -10, -8, -3, -12, 2, -1, -19, 2, 1, 9]
print(x[10])
print(x.index(1,0,5))
import numpy as np
x_arrays = np.array([7, 14, 20, 1, -16, -10, -8, -3, -12, 2, -1, -19, 2, 1, 9])
print(np.where(x_arrays == -12))

-1
3
(array([8], dtype=int32),)


In [60]:
x = [7, 14, 20, 1, -16, -10, -8, -3, -12, 2, -1, -19, 2, 1, 9]
print(len(x))
print(max(x))
print(min(x))
print(sum(x))
import numpy as np
x_array = np.array([7, 14, 20, 1, -16, -10, -8, -3, -12, 2, -1, -19, 2, 1, 9])
print(x_array.size)

15
20
-19
-13
15


Data

Task 1.
Create a list and name it as data. Insert 10 different values manually into the list without using numpy.


In [61]:
data = [1 , 5, 7, 3, 4, 9, 13, 4, 16, 12]

Task 2.
Use the list that you have created from the previous task, find...
1. The item with index of 5
2. The sum of list
3. The average of list

In [65]:
data = [1 , 5, 7, 3, 4, 9, 13, 4, 16, 12]
print(data[5])
print(sum(data))
print(sum(data) / len(data))

9
74
7.4


Task 3.
Now, create an empty list and name it as temperatures. 
Insert 20 different values into the list in the range of -60 to 60 without using numpy.

In [66]:
temperature = []
for i in range(20):
    data.append(random.randint(-60,60))
print(data)    

[1, 5, 7, 3, 4, 9, 13, 4, 16, 12, -13, -29, 28, -7, 19, 42, -23, 33, -11, 4, 60, -16, -13, -53, 2, -27, -10, -46, -22, 38]


Task 4.
Use the list that you have created from the previous task, find...
1. Maximum value of the list
2. Minimum value of the list
3. The sum of the list

In [70]:
temperature = []
for i in range(20):
    data.append(random.randint(-60,60))
print(max(data))   
print(min(data))
print(sum(data))

60
-60
190


Task 5.
Create an empty list and name it as data. Insert a range of values between 10 to 50 and set the space between each of the number to 3. The length of the list will be 30. Use numpy.

In [76]:
import numpy as np
data = []
data = np.arange(10, 50, 3, dtype=None)
print(data)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


Task 6.
From the list that you created from Task 5, find...
1. The number with index of 10
2. Find the summation between these number:
number with index 2, 4, 8 and 13

In [82]:
import numpy as np
data = []
data = np.arange(10, 50, 3, dtype=None)
print(data[10])
print(data[2] + 4 + 8 + 13)

40
41


Task 7.
Create an empty list and name it myData. After that, fill the list up with random number between that range of -500 and 500. Set the length of the list to 50. Use numpy.

In [85]:
import numpy as np
myData = []
myData = np.random.randint(-500, 500, 50)
print(myData)

[ 447  495 -425  440 -344  -24   71  314  236 -336  -41   23  408  315
  492   53  216 -262  207  314  231  245 -219  157 -426 -121  180 -175
 -421  275  254   35 -391  -28 -436  169  -35 -196 -140   90 -400 -246
   35  440  273 -346 -118  396 -216 -294]


Task 8.
From the list that you created from Task 7, find...
1. The number with index of 43
2. Max value of the list
3. The average of the list

In [87]:
import numpy as np
myData = []
myData = np.random.randint(-500, 500, 50)
print(myData[43])
print(max(data))
print(sum(data) / len(data))

466
49
29.5


Task 9.
Below shows a list that contains various of numbers. Try to find...
1. The length of the list
2. The number with index of 28
3. Location of number 452.
4. The difference between Max and Min value

In [125]:
import random
import numpy as np

lists = np.random.randint(-500, 500, np.random.randint(100, 500))
print(len(lists))
print(lists[28])
print(np.where(lists == 500))
print(max(lists) - min(lists))

177
225
(array([], dtype=int32),)
982


Task 10.
Below shows a list that contains some numbers. Try to find...
1. The difference between the number with index of 232 and 438
2. The average of list
3. Location of number 769 and -776. Built a condition for this if the number cannot be found.

In [ ]:
import random
import numpy as np
np.random.seed(0)
myList = np.random.randint(-1000, 1000, np.random.randint(500, 1000))
print(myList)
print(myList[232] - myList[438])
print(sum(myList) / len(myList))
print(np.where(myList=222))
    