Task 10.
Below shows a list that contains some numbers. Try to find...
1. The difference between the number with index of 232 and 438
2. The average of list
3. Location of number 769 and -776. Built a condition for this if the number cannot be found.

In [4]:
import random
import numpy as np
np.random.seed(0)
myList = np.random.randint(-1000, 1000, np.random.randint(500, 1000))
print(myList[232] - myList[438])


656


In [5]:
print(sum(myList) / len(myList))


-1.2157738095238095


In [8]:
b=np.where(myList==-914)
print(b)


(array([172], dtype=int32),)


In [9]:
print(np.where(myList==578))

(array([137, 185], dtype=int32),)


List: Count and Sort

Count

In [11]:
data1 = [6, 3, 1, 4, 6, 5, 9, 2, 9, 4, 7, 10, 7, 3, 1, 3, 3, 7, 1, 1]
print(data1.count(3))

4


In [12]:
import numpy as np
data2 = np.array([5, 1, 9, 4, 9, 2, 3, 5, 9, 7, 9, 3, 9, 3, 5, 2, 1, 5, 4, 2])
print(np.count_nonzero(data2 == 9))

5


Sort

In [15]:
data1 = [6, 3, 1, 4, 6, 5, 9, 2, 9, 4, 7, 10, 7, 3, 1, 3, 3, 7, 1, 1]
data1.sort(reverse = True)
print(data1)

[10, 9, 9, 7, 7, 7, 6, 6, 5, 4, 4, 3, 3, 3, 3, 2, 1, 1, 1, 1]


In [20]:
import numpy as np
data2 = np.array([5, 1, 9, 4, 9, 2, 3, 5, 9, 7, 9, 3, 9, 3, 5, 2, 1, 5, 4, 2])
data2 = np.sort(data2)
print(data2)

[1 1 2 2 2 3 3 3 4 4 5 5 5 5 7 9 9 9 9 9]


In [39]:
import random
import numpy as np
np.random.seed(0)
myData = np.random.randint(0, 1000, np.random.randint(0, 30))
myData = np.sort(myData)
print(myData)
print(np.count_nonzero(myData == 629))

[  9 192 277 359 559 629 707 723 754 763 804 835]
1


Task 1.
Without using numpy, create a list that contains 20 random number in the range of 1 to 10. Then count how many 4 does the list contains.

In [55]:
np.random.seed(0)
list =(np.random.randint(0,10,20)).tolist()

print(list) 

print(list.count(4)) 


[5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6, 8, 8, 1, 6, 7, 7, 8, 1]
1


Task 2.
Use the list that you have created from the previous task, now, arrange the elements inside the list in accending order.

In [57]:
list.sort()
print(list)

[0, 1, 1, 2, 3, 3, 3, 4, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9]


Task 3.
Without using numpy, create a list that contains 30 random number in the range of 0 to 10. From the list, count how many 2 and 6 is contains inside the list.

In [61]:
np.random.seed(0)
list = (np.random.randint(0,10,30)).tolist()
print(list.count(2))
print(list.count(6))

1
2


Task 4.
Use the list that you have created from the previous task, now, arrange the elements inside the list in descending order.

In [62]:
list.sort(reverse = True)
print(list)

[9, 9, 9, 8, 8, 8, 8, 7, 7, 7, 7, 6, 6, 5, 5, 5, 5, 4, 4, 3, 3, 3, 3, 3, 2, 1, 1, 0, 0, 0]


Task 5.
Using numpy, create a list that contains 20 random number in the range of 10 to 20. Then count how many 15 does the list contains.

In [66]:
import random
import numpy as np
np.random.seed(0)
list = (np.random.randint(10,20,20))
list = np.sort(list)
print(np.count_nonzero(list == 15))

2


Task 6.
Use the list that you have created from the previous task, now, arrange the elements inside the list.

In [67]:
list.sort()
print(list)

[10 11 11 12 13 13 13 14 15 15 16 16 17 17 17 17 18 18 18 19]


Task 7.
Using numpy, create a list that contains 50 random number in the range of -10 to 10. From the list, count how many -5 and 5 is contains inside the list.

In [71]:
import random
import numpy as np
np.random.seed(0)
list = (np.random.randint(-10,10,50))
print(np.count_nonzero(list == -5))
print(np.count_nonzero(list == 5))

3
3


Task 8.
Use the list that you have created from the previous task, now, arrange the elements inside the list.

In [72]:
list.sort()
print(list)

[-10 -10 -10 -10 -10 -10  -9  -9  -8  -7  -7  -7  -7  -6  -6  -5  -5  -5
  -4  -4  -4  -3  -3  -3  -2  -1  -1  -1   0   1   2   2   3   4   4   5
   5   5   6   7   7   8   8   8   9   9   9   9   9   9]


Task 9.
Using numpy, create a list that contains 200 random numbers in the range of -20 to 20. Find
1. the average of the list
2. the differance between the largest number and the smallest number
3. find how many times 7 appears in the list and find the total of it

In [79]:
import random
import numpy as np
np.random.seed(0)
list = (np.random.randint(-20,20,200))
print(sum(list) / len(list))
print(max(list) - min(list))
print(np.count_nonzero(list == 7))

-1.03
39
3


Task 10.
Use numpy. 
Below shows a list that contains 20 random number in the range(10, 20). Do:
1. add more elements into the list that will make up the list to have 500 elements. Set the range of elements in the list to (-30, 30)
2. find how many times 21 appears in the list
3. arrange the list

In [116]:
import numpy as np
np.random.seed(0)
data5 = np.random.randint(-30,30,500)
print(np.count_nonzero(data5 == 21))
np.sort(data5)


9


array([-30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30, -30,
       -29, -29, -29, -29, -29, -29, -29, -29, -28, -28, -28, -28, -28,
       -28, -28, -27, -27, -27, -27, -27, -27, -27, -27, -27, -27, -27,
       -27, -27, -27, -27, -26, -26, -26, -26, -26, -26, -25, -25, -25,
       -25, -25, -25, -25, -25, -25, -24, -24, -24, -24, -24, -24, -23,
       -23, -23, -23, -23, -23, -22, -22, -22, -22, -22, -22, -22, -22,
       -22, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -20, -20,
       -20, -20, -20, -20, -19, -19, -19, -19, -19, -19, -19, -19, -19,
       -19, -19, -19, -18, -18, -18, -18, -18, -17, -17, -17, -17, -17,
       -17, -17, -17, -17, -17, -17, -16, -16, -16, -16, -16, -16, -15,
       -15, -15, -15, -15, -15, -15, -15, -14, -14, -14, -14, -14, -14,
       -14, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12, -12,
       -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11, -11,
       -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10,  -

In [114]:
import numpy as np
np.random.seed(0)
data5 = (np.random.randint(-30,30,500))
a=np.sort(data5)
b=a[::-1]
print(b)


[ 29  29  29  29  29  29  29  28  28  28  28  28  28  28  28  28  28  27
  27  27  27  27  27  27  27  27  26  26  26  26  26  26  26  26  26  25
  25  25  25  24  24  24  24  24  23  23  23  23  23  23  23  23  23  23
  23  23  23  22  22  22  22  22  22  22  22  22  21  21  21  21  21  21
  21  21  21  20  20  20  20  20  20  20  20  19  19  19  19  19  19  19
  18  18  18  18  18  18  18  17  17  17  17  17  17  17  16  16  16  16
  16  16  16  16  16  16  15  15  15  15  15  14  14  14  14  14  14  14
  13  13  13  13  13  13  13  13  12  12  12  12  12  12  12  12  12  11
  11  11  11  11  11  11  11  11  10  10  10  10  10  10  10  10  10  10
  10   9   9   9   9   9   9   9   9   9   9   9   9   8   8   8   8   8
   8   8   7   7   7   6   6   6   6   6   6   6   6   6   6   5   5   5
   5   5   5   5   5   5   5   5   5   5   5   5   4   4   4   4   4   4
   4   4   4   3   3   3   3   2   2   2   2   2   2   2   2   2   1   1
   1   1   1   1   1   0   0   0   0   0   0   0   

Append, Reverse

In [117]:
x_list = [1,2,3,4]
x_list.append(5)
print(x_list)

[1, 2, 3, 4, 5]


Task 1.
Below shows a list with contains 10 elements. Without using numpy, add another 5 more random elements in the range of (-10,10) into the list.

In [118]:
import random
data = [-10, -4, 0, 6, 5, 0, 3, 8, -7, -7]
for i in range(5):
    data.append(random.randint(-10,10))
print(data)

[-10, -4, 0, 6, 5, 0, 3, 8, -7, -7, -4, 1, 10, 10, -4]


Task 2.
Use the list that you have created from the previous task, now, remove the item with index 5 and print the list. After that, remove the item with index 10 and print the list again.

In [119]:
data.pop(5)
print(data)
data.pop(10)
print(data)

[-10, -4, 0, 6, 5, 3, 8, -7, -7, -4, 1, 10, 10, -4]
[-10, -4, 0, 6, 5, 3, 8, -7, -7, -4, 10, 10, -4]


Task 3.
Now, use the list that you have created from the previous task and reverse the elements order.

In [123]:
data.reverse()
print(data)

[-10, -4, 0, 6, 5, 3, 8, -7, -7, -4, 10, 10, -4]


Task 4.
Below shows a list with contains 5 elements. Without using numpy, add more elements into the list that will make up the list to have 20 elements. Set the range of elements in the list to (-20, 20).

In [126]:
import random
list = [15,1,15,10,3]
for i in range(15):
    list.append(random.randint(-20,20))
print(list)

[15, 1, 15, 10, 3, 16, -7, 12, -3, -18, -17, -12, -7, 16, 10, -3, 2, -16, -3, -9]


Task 5.
Use the list that you have created from the previous task, now, remove all the values that is bigger then 10 in the list.

In [127]:
for i in list:
    if i > 10:
        list.remove(i)
print(list)

[1, 10, 3, -7, -3, -18, -17, -12, -7, 10, -3, 2, -16, -3, -9]


Task 6.
Now, use the list that you have created from the previous task and reverse the elements order.

In [128]:
list.reverse()
print(list)

[-9, -3, -16, 2, -3, 10, -7, -12, -17, -18, -3, -7, 3, 10, 1]


Task 7.
Below shows a list which contains 5 elements. By using Numpy, add more elements into the list that will make up the list to have 30 elements. Set the range of elements in the list to (-30, 30)

In [130]:
import random
import numpy as np
list = np.array([3, -15, -12, -29, -15])
for i in range(30):
    list = np.append(list, [random.randint(-30,30)])
print(list)

[  3 -15 -12 -29 -15  30  14  29  30 -18 -28 -21  -3  21  15   3   5  28
  -4 -11  -5 -10 -10  25 -17  -6   6   5  -9   7   7  -4 -10   4 -15]


Task 8.
Use the list that you have created from the previous task, now, remove the values with the index of 15 and 25 in the list.

In [132]:
np.delete(list, [15])
np.delete(list, [25])
print(list)

[  3 -15 -12 -29 -15  30  14  29  30 -18 -28 -21  -3  21  15   3   5  28
  -4 -11  -5 -10 -10  25 -17  -6   6   5  -9   7   7  -4 -10   4 -15]


Task 9.
Now, use the list that you have created from the previous task and reverse the elements order.

In [133]:
np.flip(list)
print(list)

[  3 -15 -12 -29 -15  30  14  29  30 -18 -28 -21  -3  21  15   3   5  28
  -4 -11  -5 -10 -10  25 -17  -6   6   5  -9   7   7  -4 -10   4 -15]


Task 10.
Now, try to do this, by using numpy
1. Create a list that contain random values in the range of -100 to 100. Set the size of the list to be 50
2. Calculate the different between the max and min values from the list
3. Find the average of the list. Make sure that the values is in float number.
4. Reverse the elements order in the list

In [140]:
import numpy as np
list = np.random.randint(-100,100,50)
print(max(list) - min(list))
print(sum(list) / len(list))
list = np.flip(list)
print(list)

186
7.24
[-88  61  14  -7  74  78  59   0 -22  -8  14 -34  69 -35  35 -18  71 -47
  66  69 -85  58  73 -94  -6 -29  41  38  28   4 -53  88 -39 -54 -49 -10
  -2 -78  18 -74  83 -27  63 -13   9  58 -96  90   5  64]
